# Generated by Django 6.0.4 on 2026-04-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Folders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='folder',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
