# Generated by Django 6.0.4 on 2026-04-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Folders', '0002_folder_position_alter_folder_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['position', 'created_at']},
        ),
    ]
