# Generated by Django 6.0.4 on 2026-04-16 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Folders', '0003_alter_folder_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='color',
            field=models.CharField(default='#6366F1', max_length=7),
        ),
        migrations.AlterField(
            model_name='folder',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='folder',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
